name: CD Pipeline

on:
  push:
    branches:
      - main
      - feature/cd # for testing purposes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: monkeyschool.indresh.me
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            bash
            cd ~/MonkeySchool
            git pull
            cd ./code
            set -a
            source .env
            set +a
            docker compose down
            docker compose up -d
